name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONPATH: src
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install minimal test deps
        run: |
          python -m pip install -U pip
          pip install pandas pytest jsonschema
      - name: Sanity import
        run: |
          python -c "import sys,os,pathlib; print('PYTHONPATH=',os.environ.get('PYTHONPATH')); import trial_equity; print('trial_equity at:', pathlib.Path(trial_equity.__file__).resolve())"
      - name: Run pilot tests only
        run: pytest -q tests/test_pilot_ready_suite.py
