name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONPATH: src   # <-- make `python -m trial_equity.cli` work without installing the package
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install minimal test deps
        run: |
          python -m pip install -U pip
          pip install pandas pytest jsonschema
      - name: Run tests
        run: pytest -q
